/* -------------------------------------------------------------------------- */
/*                        INVOICES API                                        */
/*                                                                            */
/*  POST /api/invoices — Create an invoice                                    */
/*  GET /api/invoices — List invoices                                         */
/*  PATCH /api/invoices — Update invoice status                               */
/* -------------------------------------------------------------------------- */

import { NextRequest, NextResponse } from "next/server";
import { createClient, createAdminClient } from "@/lib/supabase/server";

/* ── POST — Create invoice ────────────────────────────────────────────────── */

export async function POST(request: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        // Verify admin role
        const { data: profile } = await supabase
            .from("users")
            .select("role")
            .eq("id", user.id)
            .single<{ role: string }>();

        if (profile?.role !== "admin") {
            return NextResponse.json({ error: "Forbidden" }, { status: 403 });
        }

        const body = await request.json();
        const { client_id, items, tax_rate = 18, due_date, notes, gst_number, billing_name, billing_address, billing_email, billing_phone } = body;

        if (!client_id || !items || items.length === 0) {
            return NextResponse.json(
                { error: "Missing required fields: client_id, items" },
                { status: 400 },
            );
        }

        const admin = createAdminClient();

        // Calculate totals
        const subtotal = items.reduce(
            (sum: number, item: { quantity: number; unit_price: number }) =>
                sum + item.quantity * item.unit_price,
            0,
        );
        const taxAmount = Math.round(subtotal * tax_rate) / 100;
        const total = subtotal + taxAmount;

        // Insert invoice
        const { data: invoice, error: invoiceError } = await admin
            .from("invoices")
            .insert({
                client_id,
                invoice_number: "", // auto-generated by trigger
                subtotal,
                tax_rate,
                tax_amount: taxAmount,
                total,
                due_date: due_date || new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
                notes: notes || null,
                gst_number: gst_number || null,
                billing_name: billing_name || null,
                billing_address: billing_address || null,
                billing_email: billing_email || null,
                billing_phone: billing_phone || null,
            })
            .select()
            .single();

        if (invoiceError || !invoice) {
            console.error("❌ Failed to create invoice:", invoiceError);
            return NextResponse.json(
                { error: "Failed to create invoice" },
                { status: 500 },
            );
        }

        // Insert line items
        const lineItems = items.map((item: { description: string; quantity: number; unit_price: number; hsn_code?: string }) => ({
            invoice_id: invoice.id,
            description: item.description,
            quantity: item.quantity,
            unit_price: item.unit_price,
            amount: item.quantity * item.unit_price,
            hsn_code: item.hsn_code || null,
        }));

        const { error: itemsError } = await admin
            .from("invoice_items")
            .insert(lineItems);

        if (itemsError) {
            console.error("❌ Failed to create invoice items:", itemsError);
            await admin.from("invoices").delete().eq("id", invoice.id);
            return NextResponse.json(
                { error: "Failed to create invoice items" },
                { status: 500 },
            );
        }

        // Log transaction
        await admin.from("transactions").insert({
            client_id,
            invoice_id: invoice.id,
            type: "invoice_generated",
            amount: total,
            description: `Invoice ${invoice.invoice_number || "N/A"} generated`,
        });

        return NextResponse.json({
            success: true,
            invoice,
        });
    } catch (error) {
        console.error("❌ Invoice creation failed:", error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : "Invoice creation failed" },
            { status: 500 },
        );
    }
}

/* ── GET — List invoices ──────────────────────────────────────────────────── */

export async function GET(request: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const { searchParams } = new URL(request.url);
        const clientId = searchParams.get("client_id");
        const status = searchParams.get("status");
        const limit = searchParams.get("limit");

        const admin = createAdminClient();

        let query = admin
            .from("invoices")
            .select(`
                *,
                items:invoice_items(*),
                client:clients(id, company, users:users(full_name, email))
            `)
            .order("created_at", { ascending: false });

        if (clientId) query = query.eq("client_id", clientId);
        if (status && status !== "all") query = query.eq("status", status);
        if (limit) query = query.limit(Number(limit));

        const { data, error } = await query;

        if (error) {
            console.error("❌ Failed to fetch invoices:", error);
            return NextResponse.json(
                { error: "Failed to fetch invoices" },
                { status: 500 },
            );
        }

        return NextResponse.json({ invoices: data });
    } catch (error) {
        console.error("❌ Invoice fetch failed:", error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : "Fetch failed" },
            { status: 500 },
        );
    }
}

/* ── PATCH — Update invoice status ────────────────────────────────────────── */

export async function PATCH(request: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const { data: profile } = await supabase
            .from("users")
            .select("role")
            .eq("id", user.id)
            .single<{ role: string }>();

        if (profile?.role !== "admin") {
            return NextResponse.json({ error: "Forbidden" }, { status: 403 });
        }

        const body = await request.json();
        const { invoice_id, status } = body;

        if (!invoice_id || !status) {
            return NextResponse.json(
                { error: "Missing required fields: invoice_id, status" },
                { status: 400 },
            );
        }

        const admin = createAdminClient();

        const updateData: Record<string, unknown> = { status };
        if (status === "paid") {
            updateData.paid_at = new Date().toISOString();
        }

        const { error } = await admin
            .from("invoices")
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            .update(updateData as any)
            .eq("id", invoice_id);

        if (error) {
            return NextResponse.json(
                { error: "Failed to update invoice" },
                { status: 500 },
            );
        }

        return NextResponse.json({ success: true });
    } catch (error) {
        console.error("❌ Invoice update failed:", error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : "Update failed" },
            { status: 500 },
        );
    }
}
